const listIcons = [
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_1.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_2.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_3.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_4.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_5.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_6.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_7.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_8.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_9.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_10.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_11.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_12.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_13.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_14.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_15.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_16.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_17.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_18.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_19.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_20.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_21.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_22.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_23.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_24.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_25.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_26.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_27.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_28.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_29.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_30.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_31.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_32.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_33.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_34.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_35.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_36.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_37.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_38.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_39.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_40.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_41.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_42.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_43.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_44.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_45.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_46.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_47.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_48.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_49.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_50.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_51.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_52.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_53.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_54.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_55.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_56.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_57.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_58.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_59.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_60.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_61.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_62.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_63.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_64.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_65.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_66.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_67.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_68.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_69.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_70.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_71.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_72.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_73.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_74.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_75.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_76.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_77.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_78.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_79.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_80.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_81.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_82.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_83.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_84.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_85.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_86.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_87.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_88.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_89.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_90.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_91.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_92.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_93.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_94.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_95.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_96.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_97.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_98.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_99.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_100.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_101.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_102.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_103.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_104.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_105.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_106.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_107.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_108.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_109.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_110.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_111.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_112.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_113.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_114.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_115.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_116.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_117.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_118.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_119.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_120.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_121.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_122.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_123.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_124.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_125.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_126.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_127.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_128.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_129.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_130.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_131.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_132.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_133.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_134.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_135.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_136.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_137.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_138.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_139.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_140.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_141.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_142.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_143.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_144.png",
    "https://qltc-tkwnc.s3.ap-southeast-1.amazonaws.com/icon_145.png",
];

const listProvinces = [
    { idProvince: "01", name: "Thành phố Hà Nội" },
    { idProvince: "79", name: "Thành phố Hồ Chí Minh" },
    { idProvince: "31", name: "Thành phố Hải Phòng" },
    { idProvince: "48", name: "Thành phố Đà Nẵng" },
    { idProvince: "92", name: "Thành phố Cần Thơ" },
    { idProvince: "02", name: "Tỉnh Hà Giang" },
    { idProvince: "04", name: "Tỉnh Cao Bằng" },
    { idProvince: "06", name: "Tỉnh Bắc Kạn" },
    { idProvince: "08", name: "Tỉnh Tuyên Quang" },
    { idProvince: "10", name: "Tỉnh Lào Cai" },
    { idProvince: "11", name: "Tỉnh Điện Biên" },
    { idProvince: "12", name: "Tỉnh Lai Châu" },
    { idProvince: "14", name: "Tỉnh Sơn La" },
    { idProvince: "15", name: "Tỉnh Yên Bái" },
    { idProvince: "17", name: "Tỉnh Hoà Bình" },
    { idProvince: "19", name: "Tỉnh Thái Nguyên" },
    { idProvince: "20", name: "Tỉnh Lạng Sơn" },
    { idProvince: "22", name: "Tỉnh Quảng Ninh" },
    { idProvince: "24", name: "Tỉnh Bắc Giang" },
    { idProvince: "25", name: "Tỉnh Phú Thọ" },
    { idProvince: "26", name: "Tỉnh Vĩnh Phúc" },
    { idProvince: "27", name: "Tỉnh Bắc Ninh" },
    { idProvince: "30", name: "Tỉnh Hải Dương" },
    { idProvince: "33", name: "Tỉnh Hưng Yên" },
    { idProvince: "34", name: "Tỉnh Thái Bình" },
    { idProvince: "35", name: "Tỉnh Hà Nam" },
    { idProvince: "36", name: "Tỉnh Nam Định" },
    { idProvince: "37", name: "Tỉnh Ninh Bình" },
    { idProvince: "38", name: "Tỉnh Thanh Hóa" },
    { idProvince: "40", name: "Tỉnh Nghệ An" },
    { idProvince: "42", name: "Tỉnh Hà Tĩnh" },
    { idProvince: "44", name: "Tỉnh Quảng Bình" },
    { idProvince: "45", name: "Tỉnh Quảng Trị" },
    { idProvince: "46", name: "Tỉnh Thừa Thiên Huế" },
    { idProvince: "49", name: "Tỉnh Quảng Nam" },
    { idProvince: "51", name: "Tỉnh Quảng Ngãi" },
    { idProvince: "52", name: "Tỉnh Bình Định" },
    { idProvince: "54", name: "Tỉnh Phú Yên" },
    { idProvince: "56", name: "Tỉnh Khánh Hòa" },
    { idProvince: "58", name: "Tỉnh Ninh Thuận" },
    { idProvince: "60", name: "Tỉnh Bình Thuận" },
    { idProvince: "62", name: "Tỉnh Kon Tum" },
    { idProvince: "64", name: "Tỉnh Gia Lai" },
    { idProvince: "66", name: "Tỉnh Đắk Lắk" },
    { idProvince: "67", name: "Tỉnh Đắk Nông" },
    { idProvince: "68", name: "Tỉnh Lâm Đồng" },
    { idProvince: "70", name: "Tỉnh Bình Phước" },
    { idProvince: "72", name: "Tỉnh Tây Ninh" },
    { idProvince: "74", name: "Tỉnh Bình Dương" },
    { idProvince: "75", name: "Tỉnh Đồng Nai" },
    { idProvince: "77", name: "Tỉnh Bà Rịa - Vũng Tàu" },
    { idProvince: "80", name: "Tỉnh Long An" },
    { idProvince: "82", name: "Tỉnh Tiền Giang" },
    { idProvince: "83", name: "Tỉnh Bến Tre" },
    { idProvince: "84", name: "Tỉnh Trà Vinh" },
    { idProvince: "86", name: "Tỉnh Vĩnh Long" },
    { idProvince: "87", name: "Tỉnh Đồng Tháp" },
    { idProvince: "89", name: "Tỉnh An Giang" },
    { idProvince: "91", name: "Tỉnh Kiên Giang" },
    { idProvince: "93", name: "Tỉnh Hậu Giang" },
    { idProvince: "94", name: "Tỉnh Sóc Trăng" },
    { idProvince: "95", name: "Tỉnh Bạc Liêu" },
    { idProvince: "96", name: "Tỉnh Cà Mau" },
].sort((a, b) => a.name.localeCompare(b.name));

module.exports = {
    listProvinces,
    listIcons,
};
